### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by RaphaelMarinier** [jacob5567/game-tech-solo-project#1]
Hi,

Would it be possible to add a license to this project, so that it's clear how it can be re-used? (FYI, I have some interest in using this project for machine learning research purposes).
The standard practice is to add a LICENSE.txt file at the root of the repository. A permissive license such as MIT's (see example) would be great.
See also github's documentation about licensing: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

Thanks!

**Comment by jacob5567** [comment]
Just added it! Thanks for letting me know!
